export const resources = {
  eng: {
    translation: {
      LOGIN: "Login",
      SIGN_UP: "Sign up",
      HOME: "Home",
      SEARCH: "Search",
      LOGIN_SYSTEM: "Sign in",
      EMAIL_ADDRESS: "Email address",
      ENTER_EMAIL: "Enter your email",
      PASSWORD: "Password",
      ENTER_PASSWORD: "Enter your password",
      REMEMBER: "Remember me",
      ADMIN: "Admin",
      USER: "User",
      SETTINGS: "Settings",
      LOGOUT: "Log out",
      YOUR_CART: "Your cart",
      YOUR_CART_EMPTY: "Your cart is empty",
      WELCOME: "Welcome to ",
      BIGGEST_SHOP: "the biggest shop of the world",
      DREAM_PRICES: "your dream prices",
      WHOSE: "Whose",
    },
  },
  ru: {
    translation: {
      LOGIN: "Войти",
      SIGN_UP: "Зарегистрироваться",
      HOME: "Главная",
      SEARCH: "Поиск",
      LOGIN_SYSTEM: "Вход в систему",
      EMAIL_ADDRESS: "Электронная почта",
      ENTER_EMAIL: "Введите вашу почту",
      PASSWORD: "Пароль",
      ENTER_PASSWORD: "Введите ваш пароль",
      REMEMBER: "Запомнить меня",
      ADMIN: "Админ",
      USER: "Пользователь",
      SETTINGS: "Настройки",
      LOGOUT: "Выйти",
      YOUR_CART: "Ваша корзина",
      YOUR_CART_EMPTY: "Ваша корзина пуста",
      WELCOME: "Добро пожаловать в ",
      BIGGEST_SHOP: "крупнейший магазин",
      DREAM_PRICES: "мир цен вашей мечты",
    },
  },
  kaz: {
    translation: {
      LOGIN: "Кіру",
      SIGN_UP: "Тіркелу",
      HOME: "Басты бет",
      SEARCH: "Іздеу",
      LOGIN_SYSTEM: "Кіру жүйесі",
      EMAIL_ADDRESS: "Электрондық пошта",
      ENTER_EMAIL: "Электрондық поштаңызды енгізіңіз",
      PASSWORD: "Құпия сөз",
      ENTER_PASSWORD: "Құпия сөзді енгізіңіз",
      REMEMBER: "Мені есте сақта",
      ADMIN: "Админ",
      USER: "Қолданушы",
      SETTINGS: "Баптаулар",
      LOGOUT: "Шығу",
      YOUR_CART: "Сіздің қоржыныңыз",
      YOUR_CART_EMPTY: "Сіздің қоржыныңыз бос",
      WELCOME: "Қош келдіңіз ",
      BIGGEST_SHOP: "ең үлкен желіге",
      DREAM_PRICES: "армандағы бағаларыңызға",
    },
  },
};
